version: '3.9'

services:
  api:
    build: .
    container_name: my_blog_api
    ports:
      - 8080:8080
    environment:
      ENV: development
      MONGO_URI: mongodb://mongo:27017/my_blog_db
    depends_on:
      - mongo
    restart: 
      unless-stopped

  mongo:
    image: mongo:latest
    container_name: my_blog_mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: 
      unless-stopped

volumes:
  mongo_data:
